<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\KiyOhSR\Block\Widget\Review\Textual;
 use Magento\Framework\Escaper;

/** @var Textual $block */
/** @var Escaper $escaper */

$uniqId = $block->getUniqueId();

$accountInfo = $block->getAccountInfo();
$reviewsCount = $accountInfo[0]['total'];
$reviewsAvgScore = $accountInfo[0]['avgRatingScore'];
$reviewsAvgRating = $accountInfo[0]['avgRating'];
?>

<section data-element="kiyoh-textual-widget-<?= $uniqId; ?>"
         class="inline-flex items-center flex-wrap gap-3 px-3 py-2
              bg-white border border-gray-200 shadow rounded-xl">
    <?php if ($block->showLogo()): ?>
        <img src="<?= $block->escapeUrl($block->getLogoUrl()); ?>" width="28" height="28"
             alt="<?= $block->escapeHtml(__('Kiyoh textual widget')); ?>" />
    <?php endif;?>

    <?php if ($block->showStars()): ?>
        <?= $block->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Magmodules_HyvaKiyOhSR::widget/helper/stars.phtml')
                ->setData('svgSize', '22')
                ->setData('percent', $reviewsAvgRating * 10)
                ->toHtml();
        ?>
    <?php endif;?>

    <div class="text pt-0.5 text-sm text-gray-700">
        <?= $block->escapeHtml(__('Our store is rated with a')); ?>
        <b><?= $block->escapeHtml($reviewsAvgScore); ?></b>
        <?= $block->escapeHtml(__('based on')); ?>
        <b>
            <?= $block->escapeHtml($reviewsCount); ?> 
            <?= $reviewsCount > 1 
                    ? $block->escapeHtml(__('reviews')) 
                    : $block->escapeHtml(__('review')); ?>
        </b>
    </div>
</section>
